# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.4

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="CZipWith class and deriving via TH"
HOMEPAGE="https://github.com/lspitzner/czipwith/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
"
src_prepare() {
        default

	cabal_chdeps \
		'base >=4.9 && <4.12' 'base >=4.9 && <4.13' \
		'template-haskell >=2.9 && <2.14' 'template-haskell >=2.9 && <2.15'
}
