# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit git-r3 haskell-cabal

DESCRIPTION="LSP server for GHC"
HOMEPAGE="https://github.com/isovector/hls-tactics-plugin#readme"
EGIT_REPO_URI="https://github.com/haskell/haskell-language-server.git"
EGIT_SUBMODULES=()

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="pedantic"

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/extra:=[profile?]
	dev-haskell/fingertree:=[profile?]
	dev-haskell/generic-lens:=[profile?]
	dev-haskell/ghc-exactprint:=[profile?]
	dev-haskell/ghc-source-gen:=[profile?]
	>=app-emacs/ghcide-0.1:=[profile?]
	>=dev-haskell/haskell-lsp-0.23:=[profile?] <dev-haskell/haskell-lsp-0.24:=[profile?]
	dev-haskell/hls-plugin-api:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/mtl:=[profile?]
	>=dev-haskell/refinery-0.3:=[profile?] <dev-haskell/refinery-0.4:=[profile?]
	>=dev-haskell/retrie-0.1.1.0:=[profile?]
	>=dev-haskell/shake-0.17.5:=[profile?]
	dev-haskell/syb:=[profile?]
	dev-haskell/text:=[profile?]
	dev-lang/ghc:=[profile?]
	>=dev-lang/ghc-8.6.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.4.0.1
"

S="${WORKDIR}/${P}/plugins/${PN}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag pedantic pedantic)
}
