# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.4

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Chops a command or program invocation into digestable pieces"
HOMEPAGE="https://github.com/lspitzner/butcher/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="butcher-dev"

RDEPEND="dev-haskell/bifunctors:=[profile?]
	dev-haskell/deque:=[profile?]
	dev-haskell/either:=[profile?]
	dev-haskell/extra:=[profile?]
	dev-haskell/free:=[profile?]
	<dev-haskell/microlens-0.5:=[profile?]
	<dev-haskell/microlens-th-0.5:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/multistate:=[profile?]
	dev-haskell/unsafe:=[profile?]
	dev-haskell/void:=[profile?]
	>=dev-lang/ghc-7.10.1:=
	butcher-dev? ( dev-haskell/hspec:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
"

src_prepare() {
        default

        cabal_chdeps \
                'base >=4.9 && <4.12' 'base >=4.9 && <4.13' \
		'containers <0.6' 'containers <0.7'
}

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag butcher-dev butcher-dev)
}
