# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.6

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Explicit imports plugin for Haskell Language Server"
HOMEPAGE="http://hackage.haskell.org/package/hls-explicit-imports-plugin"
EGIT_REPO_URI="https://github.com/haskell/haskell-language-server.git"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/ghcide:=[profile?]
	dev-haskell/haskell-lsp-types:=[profile?]
	dev-haskell/hls-plugin-api:=[profile?]
	dev-haskell/shake:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	dev-lang/ghc:=[profile?]
	>=dev-lang/ghc-7.4.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2
"
