# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.9999
#hackport: flags: -pedantic

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit git-r3 haskell-cabal
RESTRICT="test" # Requires a git repo that isn't included in the tarball

DESCRIPTION="Call hierarchy plugin for Haskell Language Server"
HOMEPAGE="https://hackage.haskell.org/package/hls-call-hierarchy-plugin"
EGIT_REPO_URI="https://github.com/haskell/haskell-language-server.git"
EGIT_COMMIT="1.3.0"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/extra:=[profile?]
	dev-haskell/ghc-api-compat:=[profile?]
	dev-haskell/ghc-paths:=[profile?]
	>=dev-haskell/ghcide-1.2:=[profile?] <dev-haskell/ghcide-1.5:=[profile?]
	>=dev-haskell/hls-plugin-api-1.1:=[profile?] <dev-haskell/hls-plugin-api-1.3:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/lsp:=[profile?]
	dev-haskell/sqlite-simple:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	>=dev-lang/ghc-8.6.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.4.0.1
"

PATCHES=(
	"${FILESDIR}"/build-with-lsp-1.2.0.1.patch
)

S="${WORKDIR}/${P}/plugins/${PN}"

src_configure() {
	haskell-cabal_src_configure \
		--flag=-pedantic
}
