# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit git-r3 haskell-cabal

DESCRIPTION="Explicit imports plugin for Haskell Language Server"
HOMEPAGE="https://hackage.haskell.org/package/hls-class-plugin"
EGIT_REPO_URI="https://github.com/haskell/haskell-language-server.git"
EGIT_SUBMODULES=()

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="app-emacs/ghcide:=[profile?]
	dev-haskell/aeson:=[profile?]
	dev-haskell/ghc-exactprint:=[profile?]
	dev-haskell/haskell-lsp:=[profile?]
	dev-haskell/hls-plugin-api:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/shake:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	dev-lang/ghc:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2
"

S="${WORKDIR}/${P}/plugins/${PN}"
