# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.1.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit git-r3 haskell-cabal

DESCRIPTION="Simple interface to some of Cabal's configuration state used by ghc-mod"
HOMEPAGE="http://hackage.haskell.org/package/cabal-helper"
SRC_URI=""
EGIT_REPO_URI="https://github.com/alanz/cabal-helper.git"
EGIT_BRANCH="cabal-new-legacy"

LICENSE="AGPL-3"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RESTRICT=test # runs external cabal and downloads things

RDEPEND=">=dev-haskell/cabal-1.14:=[profile?] <dev-haskell/cabal-4.0.0:=[profile?]
	dev-haskell/cabal-plan:=
	>=dev-haskell/mtl-2.0:=[profile?] <dev-haskell/mtl-2.3:=[profile?]
	>=dev-haskell/sha-1.6.4.4:=[profile?] <dev-haskell/sha-1.7:=[profile?]
	>=dev-haskell/semigroupoids-5.2:=[profile?] <dev-haskell/semigroupoids-5.4:=[profile?]
	>=dev-haskell/pretty-show-1.6.0:=[profile?] <dev-haskell/pretty-show-1.10:=[profile?]
	>=dev-haskell/temporary-1.2.0.4:=[profile?] <dev-haskell/temporary-1.4:=[profile?]
	>=dev-haskell/utf8-string-1.0.1.1:=[profile?] <dev-haskell/utf8-string-1.1:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/extra-1.4.10 <dev-haskell/extra-1.6 )
"

PATCHES=(
	"${FILESDIR}"/ghc-8.8.patch
	"${FILESDIR}"/cabal-3.0.patch
)

src_prepare() {
        default

        cabal_chdeps \
                'Cabal            < 2.5' 'Cabal            < 3.1' \
                'temporary        < 1.3' 'temporary        < 1.4' \
                'cabal-plan       < 0.5' 'cabal-plan       < 0.7' \
		'pretty-show      < 1.10 && >= 1.8.1' 'pretty-show      < 1.10 && >= 1.6.0' \
		'template-haskell < 2.15' 'template-haskell < 2.16'
}
