# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4

EAPI=8

CRATES="
	Inflector@0.11.4
	addr2line@0.24.2
	adler2@2.0.0
	aho-corasick@1.1.3
	ansi_term@0.12.1
	atty@0.2.14
	autocfg@1.4.0
	backtrace@0.3.74
	base64@0.12.3
	bitflags@1.3.2
	bitflags@2.9.1
	byteorder@1.5.0
	bytes@1.10.1
	cc@1.2.23
	cfg-if@1.0.0
	clap@2.34.0
	cpp@0.5.10
	cpp_build@0.5.10
	cpp_common@0.5.10
	cpp_macros@0.5.10
	crossterm@0.9.6
	crossterm_cursor@0.2.6
	crossterm_input@0.3.9
	crossterm_screen@0.2.5
	crossterm_style@0.3.3
	crossterm_terminal@0.2.6
	crossterm_utils@0.2.4
	crossterm_winapi@0.1.5
	ctor-proc-macro@0.0.5
	ctor@0.4.2
	dotenvy@0.15.7
	dtor-proc-macro@0.0.5
	dtor@0.0.6
	env_logger@0.8.4
	equivalent@1.0.2
	futures-channel@0.3.31
	futures-core@0.3.31
	futures-executor@0.3.31
	futures-io@0.3.31
	futures-macro@0.3.31
	futures-sink@0.3.31
	futures-task@0.3.31
	futures-util@0.3.31
	futures@0.3.31
	fuzzy-matcher@0.3.7
	getrandom@0.2.16
	gimli@0.31.1
	goblin@0.8.2
	hashbrown@0.15.3
	hermit-abi@0.1.19
	indexmap@2.9.0
	itoa@1.0.15
	lazy_static@1.5.0
	libc@0.2.172
	lock_api@0.4.12
	log@0.4.27
	memchr@2.7.4
	minimal-lexical@0.2.1
	miniz_oxide@0.8.8
	mio@1.0.3
	nom@7.1.3
	num-traits@0.2.19
	num_enum@0.5.11
	num_enum_derive@0.5.11
	object@0.36.7
	once_cell@1.21.3
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	parse_int@0.5.0
	pin-project-lite@0.2.16
	pin-utils@0.1.0
	plain@0.2.3
	ppv-lite86@0.2.21
	proc-macro-crate@1.3.1
	proc-macro2@1.0.95
	quote@1.0.40
	rand@0.8.5
	rand_chacha@0.3.1
	rand_core@0.6.4
	redox_syscall@0.5.12
	regex-automata@0.4.9
	regex-lite@0.1.6
	regex-syntax@0.8.5
	regex@1.11.1
	rustc-demangle@0.1.24
	ryu@1.0.20
	schemafy@0.5.2
	schemafy_core@0.5.2
	schemafy_lib@0.5.2
	scopeguard@1.2.0
	scroll@0.12.0
	scroll_derive@0.12.1
	serde@1.0.219
	serde_derive@1.0.219
	serde_json@1.0.140
	serde_repr@0.1.20
	serde_spanned@0.6.8
	shlex@1.3.0
	signal-hook-registry@1.4.5
	slab@0.4.9
	smallvec@1.15.0
	socket2@0.5.9
	strsim@0.8.0
	syn@1.0.109
	syn@2.0.101
	termios@0.3.3
	textwrap@0.11.0
	thread_local@1.1.8
	tokio-macros@2.5.0
	tokio-util@0.6.10
	tokio@1.45.0
	toml@0.8.22
	toml_datetime@0.6.9
	toml_edit@0.19.15
	toml_edit@0.22.26
	toml_write@0.1.1
	unicode-ident@1.0.18
	unicode-width@0.1.14
	unicode-xid@0.2.6
	vec_map@0.8.2
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.52.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	winnow@0.5.40
	winnow@0.7.10
	zerocopy-derive@0.8.25
	zerocopy@0.8.25
"

declare -A GIT_CRATES=(
	[weaklink]='https://github.com/vadimcn/weaklink;e11a77c73534b18c354ee98765dd20354ec45258;weaklink-%commit%/weaklink'
	[weaklink_build]='https://github.com/vadimcn/weaklink;e11a77c73534b18c354ee98765dd20354ec45258;weaklink-%commit%/weaklink_build'
)

inherit cargo

DESCRIPTION="A native debugger extension for VSCode based on LLDB"
HOMEPAGE="https://github.com/vadimcn/codelldb"
SRC_URI="https://github.com/vadimcn/codelldb/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}"

LICENSE=""
# Dependent crate licenses
LICENSE+="
	BSD-2 MIT Unicode-3.0
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"

KEYWORDS="~amd64 ~arm64"

RDEPEND="llvm-core/lldb:="

PATCHES=(
	"${FILESDIR}/fix-compile-on-musl.patch"
	"${FILESDIR}/fix-libcxx-20.patch"
)

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_prepare() {
	mkdir .cargo
	cat <<- _EOF_ > "${S}"/.cargo/config.toml
		[env]
		LLDB_INCLUDE = "/usr/include/lldb"
		LLDB_DYLIB = "/usr/lib/liblldb.so"
	_EOF_

	default
}

src_compile() {
        cargo_src_compile -p codelldb
}

src_install() {
        pushd adapter/codelldb >/dev/null
        cargo_src_install
        popd >/dev/null

	insinto /usr/lib/codelldb/scripts
	for file in adapter/scripts/*.py; do
		doins $file
	done

	insinto /usr/lib/codelldb/scripts/codelldb
	for file in adapter/scripts/codelldb/*.py; do
		doins $file
	done

	mv ${D}/usr/bin/codelldb ${D}/usr/lib/codelldb
}
