# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.4.0

EAPI=8

CRATES="
	Inflector-0.11.4
	addr2line-0.15.2
	adler-1.0.2
	aho-corasick-0.7.15
	ansi_term-0.11.0
	arrayvec-0.5.2
	atty-0.2.14
	autocfg-1.0.1
	backtrace-0.3.59
	base64-0.12.3
	bitflags-1.3.2
	bitvec-0.19.5
	byteorder-1.4.3
	bytes-1.1.0
	cc-1.0.70
	cfg-if-1.0.0
	clap-2.33.3
	cpp-0.5.6
	cpp_build-0.5.6
	cpp_common-0.5.6
	cpp_macros-0.5.6
	crossterm-0.9.6
	crossterm_cursor-0.2.6
	crossterm_input-0.3.9
	crossterm_screen-0.2.5
	crossterm_style-0.3.3
	crossterm_terminal-0.2.6
	crossterm_utils-0.2.4
	crossterm_winapi-0.1.5
	env_logger-0.8.4
	funty-1.1.0
	futures-0.3.17
	futures-channel-0.3.17
	futures-core-0.3.17
	futures-executor-0.3.17
	futures-io-0.3.17
	futures-macro-0.3.17
	futures-sink-0.3.17
	futures-task-0.3.17
	futures-util-0.3.17
	gimli-0.24.0
	hermit-abi-0.1.19
	humantime-2.1.0
	if_rust_version-1.0.0
	instant-0.1.10
	itoa-0.4.8
	lazy_static-1.4.0
	lexical-core-0.7.6
	libc-0.2.101
	lock_api-0.4.5
	log-0.4.14
	memchr-2.3.4
	miniz_oxide-0.4.4
	mio-0.7.13
	miow-0.3.7
	nom-6.2.1
	ntapi-0.3.6
	num-traits-0.2.14
	num_cpus-1.13.0
	object-0.24.0
	once_cell-1.8.0
	parking_lot-0.11.2
	parking_lot_core-0.8.5
	parse_int-0.5.0
	pin-project-lite-0.2.7
	pin-utils-0.1.0
	proc-macro-hack-0.5.19
	proc-macro-nested-0.1.7
	proc-macro2-1.0.29
	quote-1.0.9
	radium-0.5.3
	redox_syscall-0.2.10
	regex-1.4.6
	regex-syntax-0.6.25
	rustc-demangle-0.1.21
	ryu-1.0.5
	schemafy-0.5.2
	schemafy_core-0.5.2
	schemafy_lib-0.5.2
	scopeguard-1.1.0
	serde-1.0.130
	serde_derive-1.0.130
	serde_json-1.0.67
	serde_repr-0.1.7
	signal-hook-registry-1.4.0
	slab-0.4.4
	smallvec-1.6.1
	static_assertions-1.1.0
	strsim-0.8.0
	superslice-1.0.0
	syn-1.0.76
	tap-1.0.1
	termcolor-1.1.2
	termios-0.3.3
	textwrap-0.11.0
	tokio-1.11.0
	tokio-macros-1.3.0
	tokio-util-0.6.8
	unicode-width-0.1.8
	unicode-xid-0.2.2
	vec_map-0.8.2
	version_check-0.9.3
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
	winreg-0.6.2
	wyz-0.2.0
"

inherit cargo

DESCRIPTION="codelldb"
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="homepage field in Cargo.toml inaccessible to cargo metadata"
SRC_URI="https://github.com/vadimcn/vscode-lldb/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	$(cargo_crate_uris)"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="0BSD Apache-2.0 BSD BSD-2 Boost-1.0 CC0-1.0 MIT Unlicense ZLIB"
SLOT="0"
KEYWORDS="~amd64"

S="${WORKDIR}/vscode-lldb-${PV}/adapter"

src_install()
{
	into /usr/lib/codelldb
	dolib.so ../build/target/release/libcodelldb.so
	dobin ../build/target/release/codelldb
}
