# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4

EAPI=8

CRATES="
	Inflector@0.11.4
	addr2line@0.24.2
	adler2@2.0.0
	aho-corasick@1.1.3
	ansi_term@0.12.1
	atty@0.2.14
	autocfg@1.4.0
	backtrace@0.3.74
	base64@0.12.3
	bitflags@1.3.2
	bitflags@2.8.0
	byteorder@1.5.0
	bytes@1.9.0
	cc@1.2.10
	cfg-if@1.0.0
	clap@2.34.0
	cpp@0.5.10
	cpp_build@0.5.10
	cpp_common@0.5.10
	cpp_macros@0.5.10
	crossterm@0.9.6
	crossterm_cursor@0.2.6
	crossterm_input@0.3.9
	crossterm_screen@0.2.5
	crossterm_style@0.3.3
	crossterm_terminal@0.2.6
	crossterm_utils@0.2.4
	crossterm_winapi@0.1.5
	dotenvy@0.15.7
	env_logger@0.8.4
	equivalent@1.0.1
	futures-channel@0.3.31
	futures-core@0.3.31
	futures-executor@0.3.31
	futures-io@0.3.31
	futures-macro@0.3.31
	futures-sink@0.3.31
	futures-task@0.3.31
	futures-util@0.3.31
	futures@0.3.31
	fuzzy-matcher@0.3.7
	getrandom@0.2.15
	gimli@0.31.1
	goblin@0.8.2
	hashbrown@0.15.2
	hermit-abi@0.1.19
	indexmap@2.7.1
	itoa@1.0.14
	lazy_static@1.5.0
	libc@0.2.169
	lock_api@0.4.12
	log@0.4.25
	memchr@2.7.4
	minimal-lexical@0.2.1
	miniz_oxide@0.8.3
	mio@1.0.3
	nom@7.1.3
	num-traits@0.2.19
	num_enum@0.5.11
	num_enum_derive@0.5.11
	object@0.36.7
	once_cell@1.20.2
	parking_lot@0.12.3
	parking_lot_core@0.9.10
	parse_int@0.5.0
	pin-project-lite@0.2.16
	pin-utils@0.1.0
	plain@0.2.3
	ppv-lite86@0.2.20
	proc-macro-crate@1.3.1
	proc-macro2@1.0.93
	quote@1.0.38
	rand@0.8.5
	rand_chacha@0.3.1
	rand_core@0.6.4
	redox_syscall@0.5.8
	regex-automata@0.4.9
	regex-lite@0.1.6
	regex-syntax@0.8.5
	regex@1.11.1
	rustc-demangle@0.1.24
	ryu@1.0.19
	schemafy@0.5.2
	schemafy_core@0.5.2
	schemafy_lib@0.5.2
	scopeguard@1.2.0
	scroll@0.12.0
	scroll_derive@0.12.0
	serde@1.0.217
	serde_derive@1.0.217
	serde_json@1.0.137
	serde_repr@0.1.19
	shlex@1.3.0
	signal-hook-registry@1.4.2
	slab@0.4.9
	smallvec@1.13.2
	socket2@0.5.8
	strsim@0.8.0
	superslice@1.0.0
	syn@1.0.109
	syn@2.0.96
	termios@0.3.3
	textwrap@0.11.0
	thread_local@1.1.8
	tokio-macros@2.5.0
	tokio-util@0.6.10
	tokio@1.43.0
	toml_datetime@0.6.8
	toml_edit@0.19.15
	unicode-ident@1.0.16
	unicode-width@0.1.14
	unicode-xid@0.2.6
	vec_map@0.8.2
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.52.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
	winnow@0.5.40
	winreg@0.6.2
	zerocopy-derive@0.7.35
	zerocopy@0.7.35
"

declare -A GIT_CRATES=(
	[weaklink]='https://github.com/vadimcn/weaklink;37f3ffaa904dd57308e745ce0950a427971c0c22;weaklink-%commit%/weaklink'
	[weaklink_build]='https://github.com/vadimcn/weaklink;37f3ffaa904dd57308e745ce0950a427971c0c22;weaklink-%commit%/weaklink_build'
)

inherit cargo

DESCRIPTION="A native debugger extension for VSCode based on LLDB"
HOMEPAGE="https://github.com/vadimcn/codelldb"
SRC_URI="https://github.com/vadimcn/codelldb/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}"

LICENSE=""
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD-2 MIT Unicode-3.0"
SLOT="0"

KEYWORDS="~amd64 ~arm64"

RDEPEND="llvm-core/lldb:="

PATCHES=(
	"${FILESDIR}/fix-compile-on-musl.patch"
	"${FILESDIR}/fix-libcxx-20.patch"
)

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_prepare() {
	mkdir .cargo
	cat <<- _EOF_ > "${S}"/.cargo/config.toml
		[env]
		LLDB_INCLUDE = "/usr/include/lldb"
		LLDB_LINK_LIB = "lldb"
		LLDB_LINK_SEARCH = "/usr/lib"
	_EOF_

	default
}

src_compile() {
        cargo_src_compile -p codelldb
}

src_install() {
        pushd adapter/codelldb >/dev/null
        cargo_src_install
        popd >/dev/null

	insinto /usr/lib/codelldb/scripts
	for file in adapter/scripts/*.py; do
		doins $file
	done

	insinto /usr/lib/codelldb/scripts/codelldb
	for file in adapter/scripts/codelldb/*.py; do
		doins $file
	done

	mv ${D}/usr/bin/codelldb ${D}/usr/lib/codelldb
}
