# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.4

EAPI=8

CRATES="
	Inflector@0.11.4
	addr2line@0.21.0
	adler@1.0.2
	aho-corasick@1.1.2
	ansi_term@0.12.1
	atty@0.2.14
	autocfg@1.1.0
	backtrace@0.3.69
	base64@0.12.3
	bitflags@1.3.2
	byteorder@1.5.0
	bytes@1.5.0
	cc@1.0.83
	cfg-if@1.0.0
	clap@2.34.0
	cpp@0.5.9
	cpp_build@0.5.9
	cpp_common@0.5.9
	cpp_macros@0.5.9
	crossterm@0.9.6
	crossterm_cursor@0.2.6
	crossterm_input@0.3.9
	crossterm_screen@0.2.5
	crossterm_style@0.3.3
	crossterm_terminal@0.2.6
	crossterm_utils@0.2.4
	crossterm_winapi@0.1.5
	dotenvy@0.15.7
	env_logger@0.8.4
	equivalent@1.0.1
	futures-channel@0.3.29
	futures-core@0.3.29
	futures-executor@0.3.29
	futures-io@0.3.29
	futures-macro@0.3.29
	futures-sink@0.3.29
	futures-task@0.3.29
	futures-util@0.3.29
	futures@0.3.29
	fuzzy-matcher@0.3.7
	getrandom@0.2.11
	gimli@0.28.1
	hashbrown@0.14.3
	hermit-abi@0.1.19
	hermit-abi@0.3.3
	indexmap@2.1.0
	itoa@1.0.9
	lazy_static@1.4.0
	libc@0.2.150
	lock_api@0.4.11
	log@0.4.20
	memchr@2.6.4
	minimal-lexical@0.2.1
	miniz_oxide@0.7.1
	mio@0.8.9
	nom@7.1.3
	num-traits@0.2.17
	num_cpus@1.16.0
	num_enum@0.5.11
	num_enum_derive@0.5.11
	object@0.32.1
	once_cell@1.18.0
	parking_lot@0.12.1
	parking_lot_core@0.9.9
	parse_int@0.5.0
	pin-project-lite@0.2.13
	pin-utils@0.1.0
	plain@0.2.3
	ppv-lite86@0.2.17
	proc-macro-crate@1.3.1
	proc-macro2@1.0.70
	quote@1.0.33
	rand@0.8.5
	rand_chacha@0.3.1
	rand_core@0.6.4
	redox_syscall@0.4.1
	regex-automata@0.4.3
	regex-syntax@0.8.2
	regex@1.10.2
	rustc-demangle@0.1.23
	ryu@1.0.15
	schemafy@0.5.2
	schemafy_core@0.5.2
	schemafy_lib@0.5.2
	scopeguard@1.2.0
	scroll@0.11.0
	scroll_derive@0.11.1
	serde@1.0.193
	serde_derive@1.0.193
	serde_json@1.0.108
	serde_repr@0.1.17
	signal-hook-registry@1.4.1
	slab@0.4.9
	smallvec@1.11.2
	socket2@0.5.5
	strsim@0.8.0
	superslice@1.0.0
	syn@1.0.109
	syn@2.0.39
	termios@0.3.3
	textwrap@0.11.0
	thread_local@1.1.7
	tokio-macros@2.2.0
	tokio-util@0.6.10
	tokio@1.34.0
	toml_datetime@0.6.5
	toml_edit@0.19.15
	unicode-ident@1.0.12
	unicode-width@0.1.11
	unicode-xid@0.2.4
	vec_map@0.8.2
	wasi@0.11.0+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.48.0
	windows-targets@0.48.5
	windows_aarch64_gnullvm@0.48.5
	windows_aarch64_msvc@0.48.5
	windows_i686_gnu@0.48.5
	windows_i686_msvc@0.48.5
	windows_x86_64_gnu@0.48.5
	windows_x86_64_gnullvm@0.48.5
	windows_x86_64_msvc@0.48.5
	winnow@0.5.25
	winreg@0.6.2
"

declare -A GIT_CRATES=(
	[goblin]='https://github.com/vadimcn/goblin;a22d2d778a25ed86f8539bf66f6ac7fcf3216815;goblin-%commit%'
	[weaklink]='https://github.com/vadimcn/weaklink;0b2873feeb402b34f2fc404507f8dc2aac15e507;weaklink-%commit%/weaklink'
	[weaklink_build]='https://github.com/vadimcn/weaklink;0b2873feeb402b34f2fc404507f8dc2aac15e507;weaklink-%commit%/weaklink_build'
)

inherit cargo

DESCRIPTION="A native debugger extension for VSCode based on LLDB"
HOMEPAGE="https://github.com/vadimcn/codelldb"
SRC_URI="https://github.com/vadimcn/codelldb/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}"

S="${WORKDIR}/${P}/adapter/codelldb"

LICENSE=""
# Dependent crate licenses
LICENSE+=" Apache-2.0 BSD-2 MIT Unicode-DFS-2016"
SLOT="0"

KEYWORDS="~amd64 ~arm64"

RDEPEND="dev-debug/lldb"

PATCHES=(
	"${FILESDIR}/fix-compile-on-musl.patch"
)

# rust does not use *FLAGS from make.conf, silence portage warning
# update with proper path to binaries this crate installs, omit leading /
QA_FLAGS_IGNORED="usr/bin/${PN}"

src_prepare() {
	mkdir .cargo
	cat <<- _EOF_ > "${S}"/.cargo/config.toml
		[env]
		LLDB_INCLUDE = "/usr/include/lldb"
		LLDB_LINK_LIB = "lldb"
		LLDB_LINK_SEARCH = "/usr/lib"
	_EOF_

	default
}

