# ebuild generated by hackport 0.4.7.9999

CABAL_FEATURES="bin"
inherit haskell-cabal

DESCRIPTION="Persistent GHC powered background server for FAST haskell development tools"
HOMEPAGE="https://github.com/hdevtools/hdevtools/"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/cmdargs
	dev-haskell/ghc-paths
	dev-haskell/network
	dev-haskell/syb
	dev-haskell/transformers
	>=dev-lang/ghc-7.4.1
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"
