# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Types and parsers for software version numbers"
HOMEPAGE="https://gitlab.com/fosskers/versions"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/hashable-1.2:=[profile?] <dev-haskell/hashable-1.3:=[profile?]
	>=dev-haskell/megaparsec-7:=[profile?] <dev-haskell/megaparsec-9:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-lang/ghc-7.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.2.0
	test? ( dev-haskell/base-prelude
		>=dev-haskell/checkers-0.4 <dev-haskell/checkers-0.5
		>=dev-haskell/microlens-0.4 <dev-haskell/microlens-0.5
		>=dev-haskell/quickcheck-2.9 <dev-haskell/quickcheck-2.13
		>=dev-haskell/tasty-0.10.1.2
		>=dev-haskell/tasty-hunit-0.9.2
		>=dev-haskell/tasty-quickcheck-0.8 <dev-haskell/tasty-quickcheck-0.11 )
"
