# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.3.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit git-r3 haskell-cabal

MY_PN="HaRe"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="the Haskell Refactorer"
HOMEPAGE="https://github.com/alanz/HaRe/wiki"
SRC_URI=""
EGIT_REPO_URI="https://github.com/alanz/HaRe.git"
EGIT_BRANCH="ghc-8.8"
EGIT_SUBMODULES=()

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RESTRICT=test # tests build a lot of time

RDEPEND="
	=dev-haskell/cabal-helper-9999:=[profile?]
	>=dev-haskell/ghc-exactprint-0.6.1:=[profile?]
	>=dev-haskell/gitrev-1.1:=[profile?]
	=dev-haskell/hie-plugin-api-9999:=[profile?]
	dev-haskell/hslogger:=[profile?]
	dev-haskell/monad-control:=[profile?]
	dev-haskell/mtl:=[profile?]
	dev-haskell/strafunski-strategylib:=[profile?]
	dev-haskell/syb:=[profile?]
	dev-haskell/syz:=[profile?]
	>=dev-lang/ghc-8.8:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.22.4.0
"

PATCHES=(
	"${FILESDIR}"/ghc-8.8.patch
)
