# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.5.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit git-r3 haskell-cabal

DESCRIPTION="A documentation-generation tool for Haskell libraries"
HOMEPAGE="http://www.haskell.org/haddock/"
SRC_URI=""
EGIT_REPO_URI="https://github.com/haskell/haddock.git"

LICENSE="BSD"
SLOT="0/${PV}"
# keep in sync with ghc-8.8
KEYWORDS=""
IUSE=""

RDEPEND="
	>=dev-lang/ghc-8.6:=[profile?] <dev-lang/ghc-8.9:=[profile?]
	>=dev-lang/ghc-8.6.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.4.0.1
	test? ( >=dev-haskell/hspec-2.4.4 <dev-haskell/hspec-2.7
		>=dev-haskell/quickcheck-2.11 <dev-haskell/quickcheck-2.13 )
"

S=${WORKDIR}/${P}/${PN}
