# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Library and utiltity for processing cabal's plan.json file"
HOMEPAGE="http://hackage.haskell.org/package/cabal-plan"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="GPL-3"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="_"

RDEPEND=">=dev-haskell/base16-bytestring-0.1.1:=[profile?] <dev-haskell/base16-bytestring-0.2:=[profile?]
	>=dev-haskell/text-1.2.2:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/vector-0.12.0.1:=[profile?] <dev-haskell/vector-0.13:=[profile?]
	>=dev-haskell/aeson-1.2.0:=[profile?] <dev-haskell/aeson-1.5:=[profile?]
	>=dev-haskell/base-orphans-0.6:=[profile?] <dev-haskell/base-orphans-0.9:=[profile?]
        >=dev-haskell/base-compat-0.9.3:=[profile?] <dev-haskell/base-compat-0.11:=[profile?]
	dev-lang/ghc:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.0
"

src_prepare() {
        default

        cabal_chdeps \
                'optparse-applicative < 0.15 && >= 0.13.0.0' 'optparse-applicative < 0.16 && >= 0.13.0.0'
}


src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag _ _)
}
