# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

# ebuild generated by hackport 0.5.4

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A standard library for Haskell"
HOMEPAGE="https://github.com/commercialhaskell/rio"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-7.4.1:=
	dev-haskell/unlift-io
	dev-haskell/bytestring:=
	dev-haskell/containers:=
	dev-haskell/deepseq:=
	dev-haskell/directory:=
	dev-haskell/exceptions:=
	dev-haskell/filepath:=
	dev-haskell/hashable:=
	dev-haskell/microlens:=
	dev-haskell/mtl:=
	dev-haskell/primitive:=
	dev-haskell/process:=
	dev-haskell/text:=
	dev-haskell/time:=
	>=dev-haskell/typed-process-0.2.2.0:=
	>=dev-haskell/unliftio-0.2.6.0:=
	dev-haskell/unordered-containers:=
	dev-haskell/vector:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.10
"
