# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit git-r3 haskell-cabal

DESCRIPTION="Common residence package of ExactPrint related tree-transformation utilities for HLS plugins (ported from tactics plugin)"
HOMEPAGE="https://github.com/haskell/haskell-language-server/hls-exactprint-utils"
SRC_URI=""
EGIT_REPO_URI="https://github.com/haskell/haskell-language-server.git"

LICENSE=""	# FIXME: EULA-style licence. Please pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="pedantic"

RDEPEND="dev-haskell/dlist:=[profile?]
	dev-haskell/ghc-exactprint:=[profile?]
	app-emacs/ghcide:=[profile?]
	dev-haskell/haskell-lsp-types:=[profile?]
	dev-haskell/hls-plugin-api:=[profile?]
	dev-haskell/retrie:=[profile?]
	dev-haskell/syb:=[profile?]
	dev-haskell/text:=[profile?]
	dev-lang/ghc:=[profile?]
	>=dev-lang/ghc-8.6.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.4.0.1
"

S="${WORKDIR}/${P}/${PN}"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag pedantic pedantic)
}
